version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: tasklist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasklist?currentSchema=tasklist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty1!
    ports:
      - '8081:8080'


  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty1!
      - POSTGRES_DB=tasklist
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
